--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/hildy/Pictures/Wallpapers/sky.jpg"

-- Special
background="#02050b"
foreground="#bfc0c2"
cursor="#bfc0c2"

-- Colors
color0="#02050b"
color1="#3f3f53"
color2="#844833"
color3="#8e694e"
color4="#212a60"
color5="#234268"
color6="#40516d"
color7="#808285"
color8="#414348"
color9="#55546F"
color10="#B16045"
color11="#BE8D69"
color12="#2D3981"
color13="#2F598B"
color14="#566D92"
color15="#bfc0c2"
