# Shell variables
# Generated by 'wal'
wallpaper="/home/hildy/Pictures/Wallpapers/sky.jpg"

# Special
background='#02050b'
foreground='#bfc0c2'
cursor='#bfc0c2'

# Colors
color0='#02050b'
color1='#3f3f53'
color2='#844833'
color3='#8e694e'
color4='#212a60'
color5='#234268'
color6='#40516d'
color7='#808285'
color8='#414348'
color9='#55546F'
color10='#B16045'
color11='#BE8D69'
color12='#2D3981'
color13='#2F598B'
color14='#566D92'
color15='#bfc0c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
